apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kubehub-cluster-01
  region: ap-northeast-1
  version: "1.23"
  
managedNodeGroups:
  - name: managed-ng-1
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 2
    maxSize: 10
    volumeSize: 10
    volumeType: gp2
